# Table of 2 with format string
a = (input("enter no. for table"))
print(a)
print(f"{a}x1 ={a}")
print(f"{a}x2 ={a*2}")
print(f"{a}x3 ={a*3}")
print(f"{a}x4 ={a*4}")
print(f"{a}x5 ={a*5}")
print(f"{a}x6 ={a*6}")
print(f"{a}x7 ={a*7}")
print(f"{a}x8 ={a*8}")
print(f"{a}x9 ={a*9}")
print(f"{a}x10 ={a*10}")
